GET http://localhost:1234/comments/11
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNjkwODQ3MjQ2LCJleHAiOjE2OTA5MzM2NDZ9.oZCDSBQXsYrtbtKOIrnHiO0rJRQRT4EcoyDKMJgrZ-4

###

GET http://localhost:1234/addresses
Content-Type:application/json

{
    "postalCode": "V6T 0B4",
    "streetAddress":"6088 Walter Gage Rd"
}